import Head from "next/head";
import { Home } from "../components/Home/Home";

import type { NextPage } from "next";

const home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/spotify.png" />
      </Head>
      <Home />
    </div>
  );
};

export default home;
