// libraries
import { useContext, useEffect, useState } from "react";
import Head from "next/head";
import type { NextPage } from "next";

// components
import Login from "../components/Login";
import Dashboard from "../components/Dashboard/Dashboard";

// styling
import styles from "../styles/Home.module.css";

// hooks
import useAuth from "../hooks/useAuth";

// context
import { Context } from "../context/context";

// get access code after logging
let code: string | null = "";
if (typeof window !== "undefined")
  code = new URLSearchParams(window.location.search).get("code")!;

const Home: NextPage = () => {
  const [displayLogin, setDisplayLogin] = useState(true);
  const accessToken = useAuth(code!);
  const { setToken } = useContext(Context);

  // set the access token
  useEffect(() => {
    if (accessToken) {
      setToken(accessToken);
    }
  }, [accessToken, setToken]);

  // has the user logged in?
  // code = "" -> no,
  // code != "" -> yes

  useEffect(() => {
    setDisplayLogin(code === null);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{displayLogin ? <Login /> : <Dashboard />}</div>
    </div>
  );
};

export default Home;
